app/jobs/solidus_importer/import_job.rb
app/models/solidus_importer/import.rb
app/models/solidus_importer/row.rb
lib/solidus_importer/process_import.rb
spec/features/solidus_importer/process_import_spec.rb
spec/jobs/solidus_importer/import_job_spec.rb

A basic approach for background processing: a unique job that handles a single import with all the relative rows and attachments.
The state of the Import and Row entities permits to launch the task on the same import multiple times to:
- retry failed imports;
- continue interrupted imports (but requires that the import entity state is reset to `failed`).

Background processing

---

lib/solidus_importer/configuration.rb
lib/solidus_importer/processors/option_types.rb
lib/solidus_importer/processors/option_values.rb
spec/features/solidus_importer/import_spec.rb
spec/lib/solidus_importer/processors/option_types_spec.rb
spec/lib/solidus_importer/processors/option_values_spec.rb

Ref. #15 
Shopify allows a maximum of three key, value options to define product
attributes (I don't know if premium shops permit more options)
We map these keys into into `Spree::OptionType/OptionValue` 

Implement product options processors

---

lib/solidus_importer/configuration.rb
lib/solidus_importer/processors/address.rb
lib/solidus_importer/processors/customer.rb
spec/factories/solidus_importer_rows.rb
spec/features/solidus_importer/processors_spec.rb
spec/fixtures/solidus_importer/customer1.csv
spec/fixtures/solidus_importer/customer2.csv
spec/fixtures/solidus_importer/customers.csv
spec/lib/solidus_importer/processors/address_spec.rb
spec/lib/solidus_importer/processors/customer_spec.rb

According to [Shopify imports manual](https://help.shopify.com/en/manual/customers/import-export-customers) the email field is mapped onto `Email`, not `Email Address`.
This also improves customers import by adding a bill address where present.

Fix and improve customer processor

---

lib/solidus_importer/processors/taxon.rb
spec/factories/solidus_importer_rows.rb
spec/lib/solidus_importer/processors/taxon_spec.rb

Ref. #14 
We map the 'Tags' field (which is a comma-separated list of tag) onto a `Spree::Taxon` belonging to a `Tags` taxonomy.
We map the `Type` field onto a `Spree::Taxon` beloinging to a `Type` taxonomy.
For more info about export files format see [Shopify documentation](https://help.shopify.com/en/manual/products/import-export/using-csv#csv-files).

Add Taxon processors

---

lib/solidus_importer.rb
lib/solidus_importer/base_importer.rb
lib/solidus_importer/configuration.rb
lib/solidus_importer/post_processors/orders_recalculator.rb
lib/solidus_importer/process_import.rb
lib/solidus_importer/process_row.rb
lib/solidus_importer/processors/order.rb
spec/features/solidus_importer/processors_spec.rb
spec/lib/solidus_importer/base_importer_spec.rb
spec/lib/solidus_importer/post_processors/orders_recalculator_spec.rb
spec/lib/solidus_importer/process_import_spec.rb
spec/lib/solidus_importer/process_row_spec.rb
spec/lib/solidus_importer/processors/order_spec.rb

In this way we can define some custom post-processors to process the context after all rows are being processed. To make it works, the context is now preserved between rows processing.
We also add a basic post-processor which invokes `#recaulculate` for all created **orders**.

Store entities on context and trigger post-processors after the import

---

app/models/solidus_importer/order_updater.rb
app/models/solidus_importer/spree_core_importer_order.rb
lib/solidus_importer/base_importer.rb
lib/solidus_importer/configuration.rb
lib/solidus_importer/order_importer.rb
lib/solidus_importer/process_import.rb
lib/solidus_importer/processors/bill_address.rb
lib/solidus_importer/processors/line_item.rb
lib/solidus_importer/processors/order.rb
lib/solidus_importer/processors/payment.rb
lib/solidus_importer/processors/ship_address.rb
lib/solidus_importer/processors/shipment.rb
spec/features/solidus_importer/import_spec.rb
spec/lib/solidus_importer/base_importer_spec.rb
spec/lib/solidus_importer/order_importer_spec.rb
spec/lib/solidus_importer/processors/bill_address_spec.rb
spec/lib/solidus_importer/processors/line_item_spec.rb
spec/lib/solidus_importer/processors/order_spec.rb
spec/lib/solidus_importer/processors/payment_spec.rb
spec/lib/solidus_importer/processors/ship_address_spec.rb
spec/lib/solidus_importer/processors/shipment_spec.rb

The approach used to generate entities whenever they're encountered during CSV row parsing works well with Customers and Products models, but has some downside when importing orders. This is because the models involved have more constraints and validations on models and associated models, and you could end up having entities in inconsistent state.
For this reason we've decided to take advantage of the [Solidus order importer](https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/importer/order.rb). Order's processors won't create entities anymore, but are responsible to build the data structure needed by the aforementioned importer, which actually creates orders. The importer is invoked after the whole CSV is parsed, in the `#after_import` callback defined in a custom …

Enhance order importer

---

lib/solidus_importer/processors/shipment.rb

There was a bug in orders importer resulting in `SolidusImporter` shipping method replication. Also fix calling non-existent `super` method for `shipping_method_name`.

Fix replication of shipping methods

---

lib/solidus_importer/processors/taxon.rb
spec/lib/solidus_importer/processors/taxon_spec.rb

When processing rows that are variants, this code will get called for a product that has been previously processed by the master variant row. In this case, the taxons will already exist on the product and be in the database. This causes a validation error to be raised because the taxon cannot be added twice to the product. We can get around this by just checking if the taxon that will be added is already there.

Do not add taxon if it's on the product

---

lib/solidus_importer/processors/option_types.rb
spec/lib/solidus_importer/processors/option_types_spec.rb

While I was importing some products into a store I was working on I noticed that I seemed to be getting duplicate Spree::OptionType values in the database, and I believe it was coming from the OptionType import here. I was able to replicate the issue by first saving the option type in the specs to the database and ensure they weren't on the product.
I think this is a use case that could happen to other people too, where the OptionType already exists in the DB without it being on the product. I think this covers the existing behaviour fairly well, and ensures we don't get any duplicate records.
If there's a quicker way to link the record created by the initialize on the product from the original code to the DB let me know.

OptionTypes loaded from DB instead of off product

---

lib/solidus_importer/processors/option_values.rb
spec/lib/solidus_importer/processors/option_values_spec.rb

The Shopify CSV format specifies the OptionValue column be empty for the first row of a product with multiple variants. I believe this row becomes the master variant. I noticed when I was following the Shopify documentation that the first row for products was failing because it would attempt to make an option value with the empty string, which then causes a validation error to be thrown.
Instead we can just skip through any empty values.

Skip empty option values

---

config/initializers/spree.rb
lib/solidus_importer/processors/option_types.rb
lib/solidus_importer/processors/option_values.rb
spec/lib/solidus_importer/processors/option_values_spec.rb

Thanks for this extension. 🙏  
While working on a client, I've noticed some small bugs that I've squashed with this PR.
I've also tried to add a little bit of consistency between the processors.
Paperclip seems to have a small bug in handling the CSV MIME type. I've added a fix for that.
I hope that this can be helpful. Let me know what do you think.

Fix option types and values processors

---

lib/solidus_importer/configuration.rb
lib/solidus_importer/process_row.rb
spec/lib/solidus_importer/process_row_spec.rb

This add a new "row_exception_handler" preference which can be set to anything callable and is invoked when exceptions happen during row processing after the critical step of marking the context as unsuccessful and recording the message.
This can be used to report exceptions and the associated context to an error reporting services, something like:
```ruby
SolidusImporter::Config.row_exception_handler = -> (e, context) {
Sentry.capture_exception(e)
}
```
This addresses #50.

Add configurable row-level exception handler

---

lib/solidus_importer/order_importer.rb
lib/solidus_importer/process_import.rb
spec/lib/solidus_importer/order_importer_spec.rb

Currently, if the `after_import` method of the importer generates an error, the ProcessImport will update the import state accordingly. However, there's no way to see the reason why the process failed, which is relevant where the `after_import` does most of the persisting work, ie on `OrderImporter`.
This change simply joins all error messages found during the Order persistence and tweaks ProcessImport so that it updates the final `SolidusImporter::Import` message accordingly

Surface after_import errors

---

lib/solidus_importer/order_importer.rb
lib/solidus_importer/processors/line_item.rb
lib/solidus_importer/processors/payment.rb
lib/solidus_importer/processors/shipment.rb
spec/features/solidus_importer/import_spec.rb
spec/lib/solidus_importer/processors/payment_spec.rb

Ref. #62 
- fix how processors store attributes; this way the related attributes
won't be deleted between row processing.
- improve expectations to check multiple line items have been imported.

Import multiple Line items for the Orders

---

lib/solidus_importer/processors/taxon.rb
spec/lib/solidus_importer/processors/taxon_spec.rb

Before this commit, an empty "Tags" or "Type" cell in a CSV would cause this processor to fail.
I believe it's reasonable to assume that some products may not include tags on import. And, while I'd prefer all products be imported with a "Type" personally, I don't this this is should be a hard requirement that makes rows fail in a product import.

Process taxons if "Tags" or "Type" are empty

---

lib/solidus_importer/processors/option_values.rb
spec/lib/solidus_importer/processors/option_values_spec.rb

When the import file has more lines for each variant in order to
specify more images per variant the mapping to the variant is made
through options instead of variant sku (which is optional). As a
result of repeating the options on all lines they are also added
by the importer multiple times ending. This change avoids adding
them if already present.

Check for duplicated option values and avoid adding them

---

lib/solidus_importer/processors/variant.rb
lib/solidus_importer/testing_support/factories/solidus_importer_rows_factory.rb
spec/lib/solidus_importer/processors/variant_spec.rb

This fix takes into account the quantities specified on variant rows
and imports them on the default location. If multiple stock locations
are used we'll need a convention in the import file to specify those
locations. This change does not deal with that situation.

Import inventory quantities for variants

---

lib/solidus_importer/process_import.rb

We can't rely on the attachment path to be something we can just
`File.read` because it may not be a local file which can be opened.
Instead we can rely on Paperclip to give us an IO adapter which
is capable of reading an attachment independent from the backend.

Use Paperclip to read the Paperclip attachments

---

app/views/spree/admin/solidus_importer/imports/index.html.erb
config/locales/en.yml
spec/features/admin/solidus_importer/imports_spec.rb
spec/models/solidus_importer/import_spec.rb

It is difficult to determine the relative success of an import, without clicking
through to the edit/show page, since even one row failure will set the state.
This should provide admin users a bit better feedback on their imports.
Spec Update:
| Description | Screenshot |
| ------------- | ------------- |
| Just after creation | ![Screen Shot 2022-01-31 at 3 44 38 PM](https://user-images.githubusercontent.com/6599070/151891509-c8437db7-43f3-43d3-b9d6-0dc9d988609e.png) |
| Processing in progress | ![Screen Shot 2022-01-31 at 3 44 46 PM](https://user-images.githubusercontent.com/6599070/151891533-254028f2-d6b2-42dd-b394-fe9340136a68.png) |
| After completion | ![Screen Shot 2022-01-31 at 3 44 55 PM](https://user-images.githubusercontent.com/6599070/151891541-06a6a66d-e35b-4468-95ec-9d1f830f4 …

Display successful row count in index

---

spec/features/solidus_importer/import_spec.rb
spec/lib/solidus_importer/processors/customer_address_spec.rb
spec/lib/solidus_importer/processors/customer_spec.rb
spec/lib/solidus_importer/processors/product_spec.rb
spec/lib/solidus_importer/processors/variant_spec.rb

Specs were failing so I took a stab at fixing them. Seem to be related to `Spree::Address`. I could be wrong on some of these as I was not the original author so please let me know if I misinterpreted the intention of these specs. But hey, at least all the specs run now!
The issue with `import_spec.rb` was that the CSV file being imported contained two customers that lived in two separate provinces, however the spec was only creating a single province. Creating both provinces resolved that issue.
The issue with `customer_address_spec.rb` was more tricky. I'm no expert, but it seems that the factory cannot create a state in the incorrect country. So I created a valid state, then updated it to associate it with the wrong country.
The second issue with that spec seemed to be written for when …

Fix broken specs

---

app/models/solidus_importer/import.rb
app/models/solidus_importer/row.rb

With a fresh install of Solidus and the solidus_importer gem (using `gem "solidus_importer", github: "solidusio-contrib/solidus_importer"`), navigating to the import page in the admin GUI results in this RuntimeError:
> RuntimeError in Spree::Admin::SolidusImporter::Imports#index
> Showing `/Users/malak/.gem/ruby/3.3.2/bundler/gems/solidus_importer-109f0c1f9790/app/views/spree/admin/solidus_importer/imports/index.html.erb` where line #16 raised:
> 
> Ransack needs SolidusImporter::Import attributes explicitly allowlisted as
searchable. Define a `ransackable_attributes` class method in your `SolidusImporter::Import`
model, watching out for items you DON'T want searchable (for
example, `encrypted_password`, `password_reset_token`, `owner` or
other sensitive information). You can use the …

Define ransackable_attributes for Import and Row
